### ISSUE TITLE
Complete 276 Tasks

### ISSUE THREAD

**Issue by rogadev** [rogadev/capstone#69]
- [x] Implement automated testing.
- [x] Adapt user stories to use Gherkin format.
- [x] Add acceptance criteria to user stories.
- [x] Submit an E2E, User Acceptance Test Plan.

**Comment by rogadev** [comment]
Automated CI/CD testing was implemented on previous branches and confirmed to be working. ✅

**Comment by rogadev** [comment]
Hey @armcdonald. Can you check on the user stories I've submitted and check off "Adapt user stories to use Gherkin format" if they suite your requirements?

**Comment by armcdonald** [comment]
Gherkin test cases are okay, but user stories should still be in the format of As a ______ I want to _______ so that _____________.  The gherkin format is used for the acceptance criteria for the user stories.

UAT test plan is fine. Good work on it, but I think you are missing some details such as actual values. Test cases are more valid and bugs more easily found when the data is specific. Just saying things like "valid credentials" is okay, but incomplete.
